#!/bin/bash

# ==========================================
# Owner Property Management - 統一啟動腳本
# ==========================================
# 功能：整合開發環境啟動、服務管理、依賴檢查
# 用法：./start.sh [all|web|web-au|admin|ocr|test|menu]

set -e

# --- 配置 ---
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$PROJECT_ROOT/logs/dev"
ENV_FILE="$PROJECT_ROOT/.env"

# --- 顏色定義 ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# --- 載入環境變數 ---
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
else
    # 如果沒有 .env，提供預設值 (避免指令碼報錯，實際上應引導用戶建立)
    echo -e "${YELLOW}⚠️  警告: 未找到 .env 檔案，將使用預設設定。請確保已建立 .env 檔案以避免 Keys 洩露。${NC}"
fi

# --- 輔助函式 ---
check_command() {
    if ! command -v "$1" &> /dev/null; then
        echo -e "${RED}❌ 錯誤: 未安裝 $1${NC}"
        return 1
    fi
}

check_dependencies() {
    echo -e "${BLUE}🔍 檢查環境依賴...${NC}"
    check_command docker || exit 1
    check_command node || exit 1
    check_command supabase || exit 1
    check_command python3 || exit 1
}

ensure_log_dir() {
    mkdir -p "$LOG_DIR"
}

ensure_supabase_running() {
    echo -e "${BLUE}🐘 檢查 Supabase 狀態...${NC}"
    # 確保本地 Storage 持久化目錄存在（config.toml objects_path 使用）
    mkdir -p "$PROJECT_ROOT/supabase/storage-data/property-photos" "$PROJECT_ROOT/supabase/storage-data/property-documents"
    if docker ps --format '{{.Names}}' | grep -q "supabase_db_"; then
        echo -e "${GREEN}✅ Supabase 已在運行${NC}"
    else
        echo -e "${YELLOW}🔄 正在啟動 Supabase...${NC}"
        supabase start > /dev/null 2>&1
        echo -e "${GREEN}✅ Supabase 啟動成功${NC}"
    fi
    # 更新 SUPABASE_URL (以防萬一)
    export SUPABASE_URL=$(supabase status 2>/dev/null | grep "API URL" | awk '{print $3}')
    # 自動寫入/更新 apps/web 與 apps/superadmin 的 .env.local 中的 Supabase 變數
    ensure_web_env_supabase
    # 資料完整性檢查：storage volume 有檔案但 DB metadata 不一致時提示還原
    check_storage_integrity
}

# 從 supabase status -o env 取得 API_URL / ANON_KEY / SERVICE_ROLE_KEY，寫入或合併到 apps/web 與 apps/superadmin 的 .env.local
ensure_web_env_supabase() {
    local status_env
    status_env=$(supabase status -o env 2>/dev/null) || return 0
    local api_url anon_key service_role_key
    api_url=$(echo "$status_env" | grep '^API_URL=' | sed 's/^API_URL=//' | tr -d '"')
    anon_key=$(echo "$status_env" | grep '^ANON_KEY=' | sed 's/^ANON_KEY=//' | tr -d '"')
    service_role_key=$(echo "$status_env" | grep '^SERVICE_ROLE_KEY=' | sed 's/^SERVICE_ROLE_KEY=//' | tr -d '"')
    if [ -z "$api_url" ] || [ -z "$anon_key" ] || [ -z "$service_role_key" ]; then
        echo -e "${YELLOW}⚠️  無法取得 Supabase 金鑰，請手動設定 .env.local${NC}"
        return 0
    fi
    for app in web web-au superadmin; do
        local env_file="$PROJECT_ROOT/apps/$app/.env.local"
        if [ -f "$env_file" ]; then
            # 移除舊的 Supabase 相關變數與本腳本寫入的註解，保留其餘
            grep -v -E '^NEXT_PUBLIC_SUPABASE_URL=|^NEXT_PUBLIC_SUPABASE_ANON_KEY=|^SUPABASE_SERVICE_ROLE_KEY=|^# Auto-generated by start.sh' "$env_file" > "${env_file}.tmp"
            mv "${env_file}.tmp" "$env_file"
        fi
        # 追加本次取得的 Supabase 變數（Next.js 需 NEXT_PUBLIC_ 前綴）
        {
            echo ""
            echo "# Auto-generated by start.sh from supabase status"
            echo "NEXT_PUBLIC_SUPABASE_URL=$api_url"
            echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon_key"
            echo "SUPABASE_SERVICE_ROLE_KEY=$service_role_key"
        } >> "$env_file"
        echo -e "${GREEN}✅ 已更新 apps/$app/.env.local 的 Supabase 變數${NC}"
    done
}

check_storage_integrity() {
    local DB_URL="postgresql://postgres:postgres@127.0.0.1:54322/postgres"
    local BACKUP_DIR="$PROJECT_ROOT/apps/superadmin/backups"

    if ! command -v psql &>/dev/null; then return 0; fi

    local STORAGE_COUNT PHOTOS_COUNT BACKUP_COUNT
    STORAGE_COUNT=$(psql "$DB_URL" -t -A -c \
      "SELECT COUNT(*) FROM storage.objects WHERE bucket_id='property-photos';" 2>/dev/null || echo "-1")
    PHOTOS_COUNT=$(psql "$DB_URL" -t -A -c \
      "SELECT COUNT(*) FROM property_photos WHERE storage_path NOT LIKE 'properties/%';" 2>/dev/null || echo "-1")
    BACKUP_COUNT=$(ls -1 "$BACKUP_DIR"/backup_*.json 2>/dev/null | wc -l | tr -d ' ')

    # Warn if storage.objects is empty but backups exist (db reset happened)
    if [ "$STORAGE_COUNT" = "0" ] && [ "$BACKUP_COUNT" -gt 0 ]; then
        echo ""
        echo -e "${YELLOW}⚠️  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${YELLOW}   偵測到 Storage metadata 遺失（storage.objects 是空的）${NC}"
        echo -e "${YELLOW}   這通常是執行過 supabase db reset 導致的${NC}"
        echo -e "${YELLOW}   找到 ${BACKUP_COUNT} 個備份檔案可供還原${NC}"
        echo -e "${YELLOW}   → 請至 http://localhost:3001/superadmin/settings/backup 進行還原${NC}"
        echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
    elif [ "$STORAGE_COUNT" != "-1" ] && [ "$PHOTOS_COUNT" != "-1" ] && [ "$STORAGE_COUNT" != "$PHOTOS_COUNT" ]; then
        echo -e "${YELLOW}⚠️  storage.objects (${STORAGE_COUNT}) 與 property_photos (${PHOTOS_COUNT}) 數量不一致，建議至備份頁面執行健康檢查${NC}"
    fi
}

check_python_venv() {
    local SERVICE_DIR="$1"
    if [ ! -d "$SERVICE_DIR/venv" ]; then
        echo -e "${YELLOW}🐍 建立 Python 虛擬環境: $SERVICE_DIR${NC}"
        cd "$SERVICE_DIR"
        python3 -m venv venv
        source venv/bin/activate
        pip install -q fastapi uvicorn pydantic cryptography 'python-jose[cryptography]' supabase
        deactivate
        cd "$PROJECT_ROOT"
    fi
}

ensure_paperclip_env() {
    local paperclip_env_file="$PROJECT_ROOT/docker/paperclip/.env.paperclip"
    local default_port="3187"
    local selected_port="${PAPERCLIP_PORT:-$default_port}"
    local selected_url="${PAPERCLIP_PUBLIC_URL:-http://localhost:$selected_port}"
    local selected_image="${PAPERCLIP_IMAGE:-ghcr.io/paperclipai/paperclip:latest}"
    local selected_auto_pull="${PAPERCLIP_AUTO_PULL:-0}"
    local selected_auto_open_browser="${PAPERCLIP_AUTO_OPEN_BROWSER:-1}"
    local selected_data_dir="${PAPERCLIP_DATA_DIR:-$HOME/.paperclip-data-owner-property-management}"
    local selected_claude_oauth_token="${CLAUDE_CODE_OAUTH_TOKEN:-}"

    if [ ! -f "$paperclip_env_file" ]; then
        mkdir -p "$selected_data_dir"
        local generated_secret
        generated_secret=$(openssl rand -hex 32)
        cat > "$paperclip_env_file" << EOF
PAPERCLIP_PORT=$selected_port
PAPERCLIP_PUBLIC_URL=$selected_url
PAPERCLIP_IMAGE=$selected_image
PAPERCLIP_AUTO_PULL=$selected_auto_pull
PAPERCLIP_AUTO_OPEN_BROWSER=$selected_auto_open_browser
PAPERCLIP_DATA_DIR=$selected_data_dir
BETTER_AUTH_SECRET=$generated_secret
CLAUDE_CODE_OAUTH_TOKEN=$selected_claude_oauth_token
EOF
        echo -e "${GREEN}✅ 已建立 docker/paperclip/.env.paperclip${NC}"
    fi

    if ! grep -q '^CLAUDE_CODE_OAUTH_TOKEN=' "$paperclip_env_file" 2>/dev/null; then
        echo "CLAUDE_CODE_OAUTH_TOKEN=$selected_claude_oauth_token" >> "$paperclip_env_file"
    fi

    PAPERCLIP_PORT=$(grep '^PAPERCLIP_PORT=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    PAPERCLIP_PUBLIC_URL=$(grep '^PAPERCLIP_PUBLIC_URL=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    PAPERCLIP_IMAGE=$(grep '^PAPERCLIP_IMAGE=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    PAPERCLIP_AUTO_PULL=$(grep '^PAPERCLIP_AUTO_PULL=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    PAPERCLIP_AUTO_OPEN_BROWSER=$(grep '^PAPERCLIP_AUTO_OPEN_BROWSER=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    PAPERCLIP_DATA_DIR=$(grep '^PAPERCLIP_DATA_DIR=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    BETTER_AUTH_SECRET=$(grep '^BETTER_AUTH_SECRET=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)
    CLAUDE_CODE_OAUTH_TOKEN=$(grep '^CLAUDE_CODE_OAUTH_TOKEN=' "$paperclip_env_file" | head -n1 | cut -d= -f2-)

    PAPERCLIP_PORT="${PAPERCLIP_PORT:-3187}"
    PAPERCLIP_PUBLIC_URL="${PAPERCLIP_PUBLIC_URL:-http://localhost:$PAPERCLIP_PORT}"
    PAPERCLIP_DASHBOARD_URL="${PAPERCLIP_DASHBOARD_URL:-${PAPERCLIP_PUBLIC_URL}/VIS/agents/ceo/dashboard}"
    PAPERCLIP_IMAGE="${PAPERCLIP_IMAGE:-ghcr.io/paperclipai/paperclip:latest}"
    PAPERCLIP_AUTO_PULL="${PAPERCLIP_AUTO_PULL:-0}"
    PAPERCLIP_AUTO_OPEN_BROWSER="${PAPERCLIP_AUTO_OPEN_BROWSER:-1}"
    PAPERCLIP_DATA_DIR="${PAPERCLIP_DATA_DIR:-$HOME/.paperclip-data-owner-property-management}"
    CLAUDE_CODE_OAUTH_TOKEN="${CLAUDE_CODE_OAUTH_TOKEN:-}"

    export PAPERCLIP_PORT PAPERCLIP_PUBLIC_URL PAPERCLIP_DASHBOARD_URL PAPERCLIP_IMAGE PAPERCLIP_AUTO_PULL PAPERCLIP_AUTO_OPEN_BROWSER PAPERCLIP_DATA_DIR BETTER_AUTH_SECRET CLAUDE_CODE_OAUTH_TOKEN
}

open_paperclip_dashboard() {
    local health_url="${PAPERCLIP_PUBLIC_URL}/api/health"

    if [ "$PAPERCLIP_AUTO_OPEN_BROWSER" != "1" ]; then
        return 0
    fi

    if ! command -v open >/dev/null 2>&1; then
        return 0
    fi

    for _ in $(seq 1 20); do
        if curl -fsS "$health_url" >/dev/null 2>&1; then
            echo -e "${BLUE}🌐 開啟 Paperclip Dashboard: ${PAPERCLIP_DASHBOARD_URL}${NC}"
            open "$PAPERCLIP_DASHBOARD_URL" >/dev/null 2>&1 || true
            return 0
        fi
        sleep 1
    done

    echo -e "${YELLOW}⚠️  Paperclip 尚未完成啟動，未自動開啟 Dashboard。可手動開啟：${PAPERCLIP_DASHBOARD_URL}${NC}"
}

start_paperclip() {
    echo -e "${BLUE}📎 啟動 Paperclip (Docker)...${NC}"
    local compose_file="$PROJECT_ROOT/docker/paperclip/docker-compose.paperclip.yml"
    local env_file="$PROJECT_ROOT/docker/paperclip/.env.paperclip"
    local paperclip_container_id=""

    if [ ! -f "$compose_file" ]; then
        echo -e "${RED}❌ 找不到 Paperclip compose 設定: $compose_file${NC}"
        return 1
    fi

    ensure_paperclip_env

    paperclip_container_id=$(docker compose --env-file "$env_file" -f "$compose_file" ps -q paperclip 2>/dev/null || true)

    if [ -n "$paperclip_container_id" ] && [ "$(docker inspect -f '{{.State.Status}}' "$paperclip_container_id" 2>/dev/null || true)" = "running" ]; then
        echo -e "${GREEN}✅ Paperclip 已在運行: ${PAPERCLIP_PUBLIC_URL:-http://localhost:${PAPERCLIP_PORT:-3187}}${NC}"
        return 0
    fi

    if [ "$PAPERCLIP_AUTO_PULL" = "1" ]; then
        echo -e "${BLUE}📥 取得 Paperclip 映像檔: ${PAPERCLIP_IMAGE}${NC}"
        docker pull "${PAPERCLIP_IMAGE}" > /dev/null 2>&1 || {
            echo -e "${YELLOW}⚠️  無法預先拉取映像檔，改由 compose 直接啟動${NC}"
        }
    elif ! docker image inspect "$PAPERCLIP_IMAGE" > /dev/null 2>&1; then
        echo -e "${BLUE}📥 首次啟動，下載 Paperclip 映像檔: ${PAPERCLIP_IMAGE}${NC}"
        docker pull "$PAPERCLIP_IMAGE" > /dev/null 2>&1 || {
            echo -e "${YELLOW}⚠️  無法預先拉取映像檔，改由 compose 直接啟動${NC}"
        }
    else
        echo -e "${BLUE}⚡ 使用本機快取映像檔（可在 docker/paperclip/.env.paperclip 設 PAPERCLIP_AUTO_PULL=1 每次更新）${NC}"
    fi

    if lsof -i :"${PAPERCLIP_PORT:-3187}" > /dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  Port ${PAPERCLIP_PORT:-3187} 已被使用，若非 Paperclip 請調整 docker/paperclip/.env.paperclip 的 PAPERCLIP_PORT${NC}"
    fi

    docker compose --env-file "$env_file" -f "$compose_file" up -d
    echo -e "${GREEN}✅ Paperclip 啟動成功: ${PAPERCLIP_PUBLIC_URL:-http://localhost:${PAPERCLIP_PORT:-3187}}${NC}"
    open_paperclip_dashboard
}

update_paperclip_image() {
    echo -e "${BLUE}📦 更新 Paperclip 映像檔 (Docker)...${NC}"
    local compose_file="$PROJECT_ROOT/docker/paperclip/docker-compose.paperclip.yml"
    local env_file="$PROJECT_ROOT/docker/paperclip/.env.paperclip"

    if [ ! -f "$compose_file" ]; then
        echo -e "${RED}❌ 找不到 Paperclip compose 設定: $compose_file${NC}"
        return 1
    fi

    ensure_paperclip_env

    echo -e "${BLUE}📥 拉取最新映像檔: ${PAPERCLIP_IMAGE}${NC}"
    docker pull "$PAPERCLIP_IMAGE"

    if docker compose --env-file "$env_file" -f "$compose_file" ps -q paperclip | grep -q .; then
        echo -e "${YELLOW}🔄 重新建立 Paperclip 容器以套用新映像檔...${NC}"
        docker compose --env-file "$env_file" -f "$compose_file" up -d --force-recreate paperclip
        echo -e "${GREEN}✅ Paperclip 已更新並重啟: ${PAPERCLIP_PUBLIC_URL:-http://localhost:${PAPERCLIP_PORT:-3187}}${NC}"
    else
        echo -e "${GREEN}✅ 映像檔已更新。尚未啟動容器，之後執行 start.sh paperclip 即可使用新版本。${NC}"
    fi
}

# --- 啟動函式 ---

start_web() {
    echo -e "${BLUE}🌐 啟動 Web App (Port 3000)...${NC}"
    if lsof -i :3000 > /dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  Web App 已在運行${NC}"
    else
        cd "$PROJECT_ROOT/apps/web"
        # 判斷是否為背景模式
        if [ "$1" == "bg" ]; then
            ensure_log_dir
            nohup npm run dev > "$LOG_DIR/nextjs.log" 2>&1 &
            echo -e "${GREEN}✅ Web App (Background) 啟動成功${NC}"
        else
            osascript -e "tell application \"Terminal\" to do script \"cd '$PROJECT_ROOT/apps/web' && npm run dev\"" >/dev/null 2>&1 &
            echo -e "${GREEN}✅ Web App (Terminal) 啟動成功${NC}"
        fi
    fi
}

start_web_au() {
    echo -e "${BLUE}🦘 啟動 Web App AU (Port 3002)...${NC}"
    if lsof -i :3002 > /dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  Web App AU 已在運行${NC}"
    else
        cd "$PROJECT_ROOT/apps/web-au"
        if [ "$1" == "bg" ]; then
            ensure_log_dir
            nohup npm run dev > "$LOG_DIR/nextjs-au.log" 2>&1 &
            echo -e "${GREEN}✅ Web App AU (Background) 啟動成功${NC}"
        else
            osascript -e "tell application \"Terminal\" to do script \"cd '$PROJECT_ROOT/apps/web-au' && npm run dev\"" >/dev/null 2>&1 &
            echo -e "${GREEN}✅ Web App AU (Terminal) 啟動成功${NC}"
        fi
    fi
}

start_admin() {
    echo -e "${BLUE}🔐 啟動 Superadmin (Port 3001)...${NC}"
    if lsof -i :3001 > /dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  Superadmin 已在運行${NC}"
    else
        cd "$PROJECT_ROOT/apps/superadmin"
        if [ "$1" == "bg" ]; then
            ensure_log_dir
            nohup npm run dev > "$LOG_DIR/superadmin.log" 2>&1 &
            echo -e "${GREEN}✅ Superadmin (Background) 啟動成功${NC}"
        else
            osascript -e "tell application \"Terminal\" to do script \"cd '$PROJECT_ROOT/apps/superadmin' && npm run dev\"" >/dev/null 2>&1 &
            echo -e "${GREEN}✅ Superadmin (Terminal) 啟動成功${NC}"
        fi
    fi
}

start_ocr() {
    echo -e "${BLUE}👁️  啟動 OCR/VLM 服務 (Port 8819)...${NC}"
    local OCR_DIR="$PROJECT_ROOT/backend/ocr_service"
    
    if lsof -i :8819 > /dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  OCR 服務已在運行${NC}"
    else
        check_python_venv "$OCR_DIR"
        
        cd "$OCR_DIR"
        source venv/bin/activate
        
        # 確保必要環境變數存在 (優先使用 .env 中的設定，若無則依賴外部環境或預設)
        if [ -z "$VLM_MASTER_KEY" ]; then
             echo -e "${YELLOW}⚠️  注意: 未偵測到 VLM_MASTER_KEY，請確認 .env 設定${NC}"
        fi
        
        # 啟動
        ensure_log_dir
        nohup python minimal_app.py > "$LOG_DIR/ocr_service.log" 2>&1 &
        deactivate
        cd "$PROJECT_ROOT"
        echo -e "${GREEN}✅ OCR 服務啟動成功${NC}"
    fi
}

start_all() {
    echo -e "${BLUE}🚀 正在啟動所有服務 (背景模式)...${NC}"
    check_dependencies
    ensure_log_dir
    ensure_supabase_running
    start_web "bg"
    start_web_au "bg"
    start_admin "bg"
    start_ocr
    start_paperclip

    echo ""
    echo -e "${GREEN}🎉 所有服務啟動程序已完成${NC}"
    echo -e "   • Web App (TW):     http://localhost:3000"
    echo -e "   • Web App (AU):     http://localhost:3002"
    echo -e "   • Superadmin:       http://localhost:3001/superadmin/dashboard"
    echo -e "   • OCR Service:      http://localhost:8819"
    echo -e "   • Paperclip:        ${PAPERCLIP_PUBLIC_URL:-http://localhost:${PAPERCLIP_PORT:-3187}}"
    echo -e "   • Supabase Studio:  http://localhost:54323"
    echo -e "   • Mailpit (Email):  http://localhost:54324"
    echo -e "   • Logs:             $LOG_DIR/"
    echo ""
    echo -e "${YELLOW}📝 測試帳號資訊${NC}"
    echo -e "   • 測試 Email:       a0426788981@gmail.com"
    echo -e "   • 統一密碼:         !qaz2wsX"
    echo -e "   • 詳細資訊:         docs/operational-guides/deployment-guides/TEST_ACCOUNTS_REFERENCE.md"
}

clean_cache() {
    echo -e "${YELLOW}🧹 清除快取...${NC}"
    rm -rf "$PROJECT_ROOT/apps/web/.next"
    rm -rf "$PROJECT_ROOT/apps/web-au/.next"
    rm -rf "$PROJECT_ROOT/apps/superadmin/.next"
    echo -e "${GREEN}✅ 完成${NC}"
}

run_tests() {
    echo -e "${BLUE}🧪 執行自動化測試...${NC}"
    
    # 檢查 Superadmin 是否運行
    if ! lsof -i :3001 > /dev/null 2>&1; then
        echo -e "${YELLOW}⚠️  Superadmin (Port 3001) 未啟動，測試需要該服務運行。${NC}"
        read -p "是否自動啟動 Superadmin (背景執行)? (y/n) " answer
        if [[ "$answer" == "y" || "$answer" == "Y" ]]; then
            start_admin "bg"
            echo -e "${YELLOW}⏳ 等待 10 秒讓服務準備就緒...${NC}"
            sleep 10
        else
            echo -e "${RED}❌ 無法執行測試：目標服務未啟動${NC}"
            return 1
        fi
    fi

    cd "$PROJECT_ROOT"
    
    echo -e "${BLUE}▶️  執行登入跳轉邏輯測試...${NC}"
    if npx playwright test apps/superadmin/e2e/login-redirect.spec.ts; then
        echo -e "${GREEN}✅ 登入邏輯測試通過${NC}"
    else
        echo -e "${RED}❌ 登入邏輯測試失敗${NC}"
        # 不中斷，繼續跑截圖
    fi
    
    echo -e "${BLUE}▶️  執行截圖生成測試...${NC}"
    if npx playwright test apps/superadmin/e2e/generate-screenshots.spec.ts; then
        echo -e "${GREEN}✅ 截圖生成成功${NC}"
    else
        echo -e "${RED}❌ 截圖生成失敗${NC}"
    fi
    
    echo -e "${GREEN}✅ 測試執行程序結束${NC}"
    echo -e "   • 截圖位置: apps/superadmin/e2e/screenshots/"
}

# --- 選單介面 ---
show_menu() {
    clear
    echo -e "${BLUE}════════════════════════════════════════${NC}"
    echo -e "${BLUE}   Owner Property Management - 啟動選單 ${NC}"
    echo -e "${BLUE}════════════════════════════════════════${NC}"
    echo "1) 🚀 啟動所有服務 (背景執行)"
    echo "2) 🌐 啟動 Web App TW (Port 3000)"
    echo "3) 🦘 啟動 Web App AU (Port 3002)"
    echo "4) 🔐 啟動 Superadmin (Port 3001)"
    echo "5) 👁️  啟動 OCR/VLM 後端"
    echo "6) 🧪 執行 Superadmin 測試 (含截圖)"
    echo "7) 🧹 清除快取 (TW + AU + Superadmin)"
    echo "8) 📎 啟動 Paperclip (Docker)"
    echo "9) 📦 更新 Paperclip 映像檔"
    echo "10) 🛑 停止所有服務"
    echo "0) 離開"
    echo ""
    read -p "請輸入選項: " choice

    case $choice in
        1) start_all ;;
        2) check_dependencies; ensure_supabase_running; start_web ;;
        3) check_dependencies; ensure_supabase_running; start_web_au ;;
        4) check_dependencies; ensure_supabase_running; start_admin ;;
        5) check_dependencies; ensure_supabase_running; start_ocr ;;
        6) run_tests ;;
        7) clean_cache ;;
        8) start_paperclip ;;
        9) update_paperclip_image ;;
        10) ./stop.sh ;;
        0) exit 0 ;;
        *) echo "無效選項"; sleep 1; show_menu ;;
    esac
}

# --- 主邏輯 ---
case "${1:-menu}" in
    all)    start_all ;;
    web)    check_dependencies; ensure_supabase_running; start_web ;;
    web-au) check_dependencies; ensure_supabase_running; start_web_au ;;
    admin)  check_dependencies; ensure_supabase_running; start_admin ;;
    ocr)    check_dependencies; ensure_supabase_running; start_ocr ;;
    paperclip) check_dependencies; start_paperclip ;;
    paperclip-update) check_dependencies; update_paperclip_image ;;
    test)   run_tests ;;
    clean)  clean_cache ;;
    menu)   show_menu ;;
    *)      echo "用法: $0 [all|web|web-au|admin|ocr|paperclip|paperclip-update|test|clean|menu]" ;;
esac
