import { execFile } from 'child_process';
import { promisify } from 'util';

const execFileAsync = promisify(execFile);

const GH_PATH = '/opt/homebrew/bin/gh';

function ghEnv(): NodeJS.ProcessEnv {
  const token = process.env.GITHUB_TOKEN ?? process.env.GITHUB_PERSONAL_ACCESS_TOKEN ?? '';
  return { ...process.env, GH_TOKEN: token };
}

export interface CreatePROptions {
  branch: string;
  base?: string;
  title: string;
  body: string;
  repoRoot: string;
}

export interface PRInfo {
  url: string;
  number: number;
  state: 'OPEN' | 'MERGED' | 'CLOSED';
}

/** Push a local branch to origin. */
export async function pushBranch(branch: string, repoRoot: string): Promise<void> {
  await execFileAsync('git', ['push', 'origin', branch, '--force-with-lease'], {
    cwd: repoRoot,
    env: ghEnv(),
    timeout: 60_000,
  });
}

/** Create a GitHub PR using gh CLI. Returns the PR URL and number. */
export async function createPR(opts: CreatePROptions): Promise<PRInfo> {
  const { stdout } = await execFileAsync(
    GH_PATH,
    [
      'pr', 'create',
      '--base', opts.base ?? 'main',
      '--head', opts.branch,
      '--title', opts.title,
      '--body', opts.body,
      '--json', 'url,number,state',
    ],
    { cwd: opts.repoRoot, env: ghEnv(), timeout: 30_000 },
  );
  return JSON.parse(stdout.trim()) as PRInfo;
}

/** Get PR status for a branch. Returns null if no PR exists. */
export async function getPRStatus(branch: string, repoRoot: string): Promise<PRInfo | null> {
  try {
    const { stdout } = await execFileAsync(
      GH_PATH,
      ['pr', 'view', branch, '--json', 'url,number,state'],
      { cwd: repoRoot, env: ghEnv(), timeout: 15_000 },
    );
    return JSON.parse(stdout.trim()) as PRInfo;
  } catch {
    return null;
  }
}

/** Build a PR body from diff stats and agent info. */
export function buildPRBody(opts: {
  slug: string;
  filesChanged: number;
  insertions: number;
  deletions: number;
  commitSubjects: string[];
  agentName?: string;
}): string {
  const lines: string[] = [
    '## Summary',
    '',
    `Paperclip agent branch \`${opts.slug}\` — ${opts.filesChanged} files changed (+${opts.insertions}/-${opts.deletions})`,
    '',
  ];

  if (opts.agentName) {
    lines.push(`**Agent**: ${opts.agentName}`, '');
  }

  if (opts.commitSubjects.length > 0) {
    lines.push('## Commits', '');
    for (const s of opts.commitSubjects) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  lines.push('---', 'Auto-generated by Paperclip Mission Control');
  return lines.join('\n');
}
