-- AI Model Research Reports
-- Stores LLM-generated research reports for each validated AI model.
-- One row per (user_id, provider, model_id). Generated by a unified evaluator
-- LLM (e.g. Claude with web_search tool) and cached for fast UI display.

CREATE TABLE IF NOT EXISTS ai_model_research_reports (
  id                    UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id               UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  provider              TEXT NOT NULL,
  model_id              TEXT NOT NULL,
  model_name            TEXT NOT NULL,

  -- Structured metadata extracted by the evaluator LLM
  company_name          TEXT,
  version_label         TEXT,
  input_price_per_1m    NUMERIC,           -- USD per 1M input tokens
  output_price_per_1m   NUMERIC,           -- USD per 1M output tokens
  context_window        INTEGER,
  knowledge_cutoff      TEXT,
  capabilities          JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_urls           TEXT[] NOT NULL DEFAULT '{}',

  -- Full markdown narrative report (everything before the JSON block)
  report_markdown       TEXT NOT NULL DEFAULT '',

  -- Provenance / status
  generator_model       TEXT NOT NULL,
  generator_provider    TEXT NOT NULL,
  generation_status     TEXT NOT NULL DEFAULT 'done'
                        CHECK (generation_status IN ('pending','researching','done','failed')),
  generation_error      TEXT,

  generated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (user_id, provider, model_id)
);

COMMENT ON TABLE  ai_model_research_reports IS '模型網路評測報告：由統一評審 LLM (含 web search) 對每個已驗證模型產出的調查報告快取';
COMMENT ON COLUMN ai_model_research_reports.input_price_per_1m  IS 'USD per 1M input tokens (from official pricing page; for reference only)';
COMMENT ON COLUMN ai_model_research_reports.output_price_per_1m IS 'USD per 1M output tokens (from official pricing page; for reference only)';
COMMENT ON COLUMN ai_model_research_reports.source_urls         IS 'URLs cited by the evaluator LLM. Required to be non-empty for done reports';
COMMENT ON COLUMN ai_model_research_reports.generator_model     IS 'The LLM that produced this report (e.g. claude-opus-4-6)';

ALTER TABLE ai_model_research_reports ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ai_model_research_reports'
    AND policyname = 'Users can manage own research reports'
  ) THEN
    EXECUTE 'CREATE POLICY "Users can manage own research reports"
      ON ai_model_research_reports FOR ALL
      USING (auth.uid() = user_id)
      WITH CHECK (auth.uid() = user_id)';
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'ai_model_research_reports'
    AND policyname = 'Service role full access to research reports'
  ) THEN
    EXECUTE 'CREATE POLICY "Service role full access to research reports"
      ON ai_model_research_reports FOR ALL
      USING (auth.role() = ''service_role'')';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ai_model_research_reports_user
  ON ai_model_research_reports (user_id, provider, model_id);

CREATE INDEX IF NOT EXISTS idx_ai_model_research_reports_status
  ON ai_model_research_reports (user_id, generation_status);

CREATE OR REPLACE FUNCTION update_ai_model_research_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_ai_model_research_reports_updated_at ON ai_model_research_reports;
CREATE TRIGGER trg_ai_model_research_reports_updated_at
  BEFORE UPDATE ON ai_model_research_reports
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_model_research_reports_updated_at();
