-- ======================================================================================
-- Title: avialable_ai_models_and_version 欄位擴充與各大廠 AI 模型種子
-- Date: 2026-02-16
-- Description: 新增 provider / model_id / model_name 等欄位，並寫入 OpenAI、Anthropic、
--              Google Gemini、DeepSeek、xAI Grok 目前常用 API 模型（參考 2025 公開資訊）
-- ======================================================================================

-- 0. 若表不存在則建立（供 db reset 等情境）
CREATE TABLE IF NOT EXISTS public.avialable_ai_models_and_version (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  provider TEXT NOT NULL DEFAULT 'openai',
  model_id TEXT NOT NULL DEFAULT '',
  model_name TEXT,
  description TEXT,
  context_window_tokens INTEGER,
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 1. 若表已存在但缺欄位則補上
ALTER TABLE public.avialable_ai_models_and_version
  ADD COLUMN IF NOT EXISTS provider TEXT NOT NULL DEFAULT 'openai',
  ADD COLUMN IF NOT EXISTS model_id TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS model_name TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS context_window_tokens INTEGER,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

COMMENT ON COLUMN public.avialable_ai_models_and_version.provider IS '供應商: openai, anthropic, gemini, deepseek, grok';
COMMENT ON COLUMN public.avialable_ai_models_and_version.model_id IS 'API 使用的 model identifier';
COMMENT ON COLUMN public.avialable_ai_models_and_version.model_name IS '顯示名稱';
COMMENT ON COLUMN public.avialable_ai_models_and_version.context_window_tokens IS '最大 context 長度（tokens）';

-- 若既有資料缺少 provider/model_id，標記後刪除
UPDATE public.avialable_ai_models_and_version SET provider = 'openai', model_id = 'legacy' WHERE model_id = '' OR model_id IS NULL;
DELETE FROM public.avialable_ai_models_and_version WHERE model_id = 'legacy';

-- 先建 unique 索引，供 INSERT ON CONFLICT 使用
CREATE UNIQUE INDEX IF NOT EXISTS idx_avialable_ai_models_provider_model
  ON public.avialable_ai_models_and_version(provider, model_id);

-- 2. 寫入各大廠 AI 模型（參考 2025 公開 API 文件）
INSERT INTO public.avialable_ai_models_and_version
  (provider, model_id, model_name, description, context_window_tokens, is_active, sort_order, updated_at)
VALUES
  -- OpenAI
  ('openai', 'gpt-4o', 'GPT-4o', 'Flagship multimodal, text and image', 128000, true, 10, NOW()),
  ('openai', 'gpt-4o-mini', 'GPT-4o mini', 'Fast, lower cost', 128000, true, 11, NOW()),
  ('openai', 'gpt-4.1', 'GPT-4.1', 'Developer-optimized, 1M context', 1000000, true, 12, NOW()),
  ('openai', 'gpt-4.1-mini', 'GPT-4.1 mini', 'Smaller, strong instruction following', 128000, true, 13, NOW()),
  ('openai', 'gpt-4-turbo', 'GPT-4 Turbo', 'High intelligence, 128k context', 128000, true, 14, NOW()),
  ('openai', 'gpt-4', 'GPT-4', 'Previous flagship', 8192, true, 15, NOW()),
  ('openai', 'gpt-3.5-turbo', 'GPT-3.5 Turbo', 'Fast, routine tasks', 16385, true, 16, NOW()),
  ('openai', 'o1', 'o1', 'Advanced reasoning', 200000, true, 17, NOW()),
  ('openai', 'o1-mini', 'o1 mini', 'Reasoning, lower cost', 128000, true, 18, NOW()),
  ('openai', 'o3-mini', 'o3 mini', 'Reasoning model', 200000, true, 19, NOW()),
  -- Anthropic
  ('anthropic', 'claude-opus-4-6', 'Claude Opus 4.6', 'Most capable, complex tasks', 200000, true, 20, NOW()),
  ('anthropic', 'claude-sonnet-4-5-20250929', 'Claude Sonnet 4.5', 'Balance of speed and intelligence', 200000, true, 21, NOW()),
  ('anthropic', 'claude-haiku-4-5-20251001', 'Claude Haiku 4.5', 'Fast, near-frontier', 200000, true, 22, NOW()),
  ('anthropic', 'claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet', 'Strong general purpose', 200000, true, 23, NOW()),
  ('anthropic', 'claude-3-opus-20240229', 'Claude 3 Opus', 'Previous flagship', 200000, true, 24, NOW()),
  ('anthropic', 'claude-3-haiku-20240307', 'Claude 3 Haiku', 'Fast, efficient', 200000, true, 25, NOW()),
  -- Google Gemini
  ('gemini', 'gemini-2.5-pro', 'Gemini 2.5 Pro', 'Advanced reasoning, multimodal', 1000000, true, 30, NOW()),
  ('gemini', 'gemini-2.5-flash', 'Gemini 2.5 Flash', 'Fast, scalable', 1000000, true, 31, NOW()),
  ('gemini', 'gemini-2.0-flash', 'Gemini 2.0 Flash', 'Speed and quality', 1000000, true, 32, NOW()),
  ('gemini', 'gemini-1.5-pro', 'Gemini 1.5 Pro', 'Long context, 1M tokens', 1000000, true, 33, NOW()),
  ('gemini', 'gemini-1.5-flash', 'Gemini 1.5 Flash', 'Efficient, long context', 1000000, true, 34, NOW()),
  ('gemini', 'gemini-pro', 'Gemini Pro', 'General purpose', 30720, true, 35, NOW()),
  -- DeepSeek
  ('deepseek', 'deepseek-chat', 'DeepSeek Chat (V3.2)', 'Non-thinking, 128k context', 128000, true, 40, NOW()),
  ('deepseek', 'deepseek-reasoner', 'DeepSeek Reasoner', 'Thinking mode V3.2', 128000, true, 41, NOW()),
  ('deepseek', 'deepseek-coder', 'DeepSeek Coder', 'Code generation', 16000, true, 42, NOW()),
  -- xAI Grok
  ('grok', 'grok-4-0709', 'Grok 4', 'Flagship reasoning', 256000, true, 50, NOW()),
  ('grok', 'grok-4-fast-reasoning', 'Grok 4 Fast Reasoning', 'Cost-efficient reasoning', 2000000, true, 51, NOW()),
  ('grok', 'grok-4-fast-non-reasoning', 'Grok 4 Fast Non-Reasoning', 'Fast drafts', 2000000, true, 52, NOW()),
  ('grok', 'grok-3', 'Grok 3', 'Enterprise, coding', 131072, true, 53, NOW()),
  ('grok', 'grok-3-mini', 'Grok 3 Mini', 'Lower cost, faster', 131072, true, 54, NOW()),
  ('grok', 'grok-2', 'Grok 2', 'Previous generation', 131072, true, 55, NOW())
ON CONFLICT (provider, model_id) DO NOTHING;

-- 3. 其餘索引
CREATE INDEX IF NOT EXISTS idx_avialable_ai_models_provider ON public.avialable_ai_models_and_version(provider);
CREATE INDEX IF NOT EXISTS idx_avialable_ai_models_active ON public.avialable_ai_models_and_version(is_active) WHERE is_active = true;

-- 4. RLS
ALTER TABLE public.avialable_ai_models_and_version ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow read for authenticated" ON public.avialable_ai_models_and_version;
CREATE POLICY "Allow read for authenticated"
  ON public.avialable_ai_models_and_version FOR SELECT
  TO authenticated USING (true);

DO $$ BEGIN RAISE NOTICE 'avialable_ai_models_and_version: 已更新欄位並寫入 OpenAI/Anthropic/Gemini/DeepSeek/Grok 模型'; END $$;
